server:
  port: 8080
  context-path: /sell

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/sell?useSSL=false
    username: root
    password: 1234
  jpa:
    show-sql: true
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: F:\sell.log
#  level: debug
